(load "metacircular/common.scm")

(load "metacircular/apply.scm")
(load "metacircular/assignment.scm")
(load "metacircular/begin.scm")
(load "metacircular/conditional.scm")
(load "metacircular/definition.scm")
(load "metacircular/eval.scm")
(load "metacircular/lambda.scm")
(load "metacircular/let.scm")
(load "metacircular/quote.scm")
(load "metacircular/sequence.scm")
