(load "lib.scm")

(define native-apply apply)
(define (self-evaluating? exp)
  (cond ((number? exp) #t)
        ((string? exp) #t)
        (else #f)))

(define (adjoin-arg arg arglist)
  (append arglist (list arg)))

(define (last-operand? ops) (null? (cdr ops)))

(define (primitive-procedure-names)
  (map car eceval-operations))

(define (primitive-procedure-objects)
  (map (lambda (proc) (list 'primitive (cadr proc)))
       eceval-operations))

(define (get-global-environment)
  (setup-environment))

(define (empty-arglist) '())

(define eceval-operations
  (list (list 'self-evaluating? self-evaluating?)
        (list 'car car)
        (list 'cdr cdr)
        (list 'cons cons)
        (list 'null? null?)
        (list '+ +)
        (list '- -)
        (list '* *)
        (list '/ /)
        (list 'assignment? assignment?)
        (list 'assignment-variable assignment-variable)
        (list 'assignment-value assignment-value)
        (list 'definition? definition?)
        (list 'if? if?)
        (list 'lambda? lambda?)
        (list 'begin? begin?)
        (list 'no-operands? no-operands?)
        (list 'last-operand? last-operand?)
        (list 'adjoin-arg adjoin-arg)
        (list 'first-operand first-operand)
        (list 'rest-operands rest-operands)
        (list 'application? application?)
        (list 'make-procedure make-procedure)
        (list 'empty-arglist empty-arglist)
        (list 'operator operator)
        (list 'operands operands)
        (list 'quoted? quoted?)
        (list 'primitive-procedure? primitive-procedure?)
        (list 'compound-procedure? compound-procedure?)
        (list 'text-of-quotation text-of-quotation)
        (list 'lambda-parameters lambda-parameters)
        (list 'lambda-body lambda-body)
        (list 'variable? variable?)
        (list 'apply-primitive-procedure apply-primitive-procedure)
        (list 'procedure-parameters procedure-parameters)
        (list 'procedure-body procedure-body)
        (list 'begin-actions begin-actions)
        (list 'first-exp first-exp)
        (list 'last-exp? last-exp?)
        (list 'rest-exps rest-exps)
        (list 'if-predicate if-predicate)
        (list 'true? (lambda (e) (not (false? e))))
        (list 'false? false?)
        (list 'if-consequent if-consequent)
        (list 'if-alternative if-alternative)
        (list 'procedure-environment procedure-environment)
        (list 'extend-environment extend-environment)
        (list 'lookup-variable-value lookup-variable-value)
        (list 'set-variable-value! set-variable-value!)
        (list 'definition-variable definition-variable)
        (list 'definition-value definition-value)
        (list 'define-variable! define-variable!)
        (list 'prompt-for-input prompt-for-input)
        (list 'read read)
        (list 'user-print display)
        (list 'announce-output announce-output)
        (list 'get-global-environment get-global-environment)
        ))

(define (tagged-list? exp sym)
  (eq? (car exp) sym))


(define (user-print object)
  (if (compound-procedure? object)
    (display (list 'compound-procedure
                   (procedure-parameters object)
                   (procedure-body object)
                   '<procedure-env>))
    (display object)))

(define (variable? exp) (symbol? exp))
