(define get 2d-get)
(define put 2d-put!)

(load "components/assertion.scm")
(load "components/compound.scm")
(load "components/qeval.scm")
(load "components/exec.scm")
(load "components/fetch.scm")
(load "components/filter.scm")
(load "components/frame.scm")
(load "components/logic.scm")
(load "components/reader.scm")
(load "components/repl.scm")
(load "components/rule.scm")
(load "components/simple.scm")
(load "components/stream.scm")
(load "components/syntax.scm")
(load "components/variable.scm")

(query-driver-loop)
